apiVersion: 1

datasources:
  - name: postgres - telescope
    type: postgres
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      database: postgres
      sslmode: disable
      postgresVersion: 1700
